package com.timwe.tti2sdk.ui

enum class FragmentId {
    FRAG_HOME,
    FRAG_HEAD, FRAG_CLOTHES, FRAG_SHOES, FRAG_RIDE,
    FRAG_AVALIABLE, FRAG_HISTORY,
    FRAG_ALL_TIME, FRAG_TODAY, FRAG_WEEK, FRAG_MONTH
}